using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Lathe.UI;

[GenerateTypedNameReferences]
public sealed partial class RecipeControl : Control
{
    public Action<string>? OnButtonPressed;
    public Func<string> TooltipTextSupplier;

    private ProtoId<LatheRecipePrototype> _recipeId;
    private LatheSystem _latheSystem;

    public RecipeControl(LatheSystem latheSystem, LatheRecipePrototype recipe, Func<string> tooltipTextSupplier, bool canProduce, Control displayControl, bool alertLevelBlocked = false)
    {
        RobustXamlLoader.Load(this);

        _latheSystem = latheSystem;
        _recipeId = recipe.ID;
        TooltipTextSupplier = tooltipTextSupplier;
        SetRecipe(recipe);
        SetCanProduce(canProduce);
        SetDisplayControl(displayControl);
        SetAlertLevelBlocked(alertLevelBlocked);

        // Set the alert icon texture
        AlertLevelBlockedIcon.Texture = new TextureResource();
        AlertLevelBlockedIcon.TexturePath = "/Textures/Interface/Nano/window_header_alert.png";

        Button.OnPressed += (_) =>
        {
            OnButtonPressed?.Invoke(_recipeId);
        };
        Button.TooltipSupplier = SupplyTooltip;
    }

    public void SetRecipe(LatheRecipePrototype recipe)
    {
        RecipeName.Text = _latheSystem.GetRecipeName(recipe);
        _recipeId = recipe.ID;
    }

    public void SetTooltipSupplier(Func<string> tooltipTextSupplier)
    {
        TooltipTextSupplier = tooltipTextSupplier;
    }

    public void SetCanProduce(bool canProduce)
    {
        Button.Disabled = !canProduce;
    }

    public void SetDisplayControl(Control displayControl)
    {
        RecipeDisplayContainer.Children.Clear();
        RecipeDisplayContainer.AddChild(displayControl);
    }

    public void SetAlertLevelBlocked(bool blocked)
    {
        AlertLevelBlockedIcon.Visible = blocked;
    }

    private Control? SupplyTooltip(Control sender)
    {
        return new RecipeTooltip(TooltipTextSupplier());
    }
}
