using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared.ADT.Silicons.Borgs;
using Content.Shared.ADT.Silicons.Borgs.Components;
using Content.Shared.Guidebook;
using Content.Shared.Silicons.Borgs;
using Content.Shared.Silicons.Borgs.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.ADT.Silicons.Borgs;

/// <summary>
/// Menu used by syndicate saboteur borgs to select their chassis appearance and rename themselves.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class SaboteurChassisSwitchMenu : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    private BorgTypePrototype? _selectedBorgType;
    private BorgSubtypePrototype? _selectedBorgSubtype;

    public event Action<ProtoId<BorgSubtypePrototype>, string?>? ConfirmedChassisSelection;

    private static readonly List<ProtoId<GuideEntryPrototype>> GuidebookEntries = new() { "Cyborgs", "Robotics" };

    public SaboteurChassisSwitchMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var typeGroup = new ButtonGroup();
        foreach (var borgType in _prototypeManager.EnumeratePrototypes<BorgTypePrototype>()
            .OrderBy(PrototypeName))
        {
            var button = new Button
            {
                Text = PrototypeName(borgType),
                Group = typeGroup,
            };
            button.OnPressed += _ =>
            {
                _selectedBorgType = borgType;
                UpdateChassisSelection(borgType);
            };
            TypeSelectionsContainer.AddChild(button);
        }

        ConfirmChassisButton.OnPressed += ConfirmButtonPressed;
        HelpGuidebookIds = GuidebookEntries;
        ConfirmChassisButton.Disabled = true;
    }

    private void UpdateChassisSelection(BorgTypePrototype borgType)
    {
        ChassisSelectionsContainer.RemoveAllChildren();
        
        var chassisGroup = new ButtonGroup();
        var subtypes = _prototypeManager
            .EnumeratePrototypes<BorgSubtypePrototype>()
            .Where(s => s.ParentBorgType == borgType)
            .OrderBy(PrototypeName)
            .ToList();

        if (subtypes.Count == 0)
        {
            ChassisSelectionsContainer.AddChild(new Label
            {
                Text = Loc.GetString("borg-subtype-selection-none-available"),
                HorizontalAlignment = HAlignment.Center
            });
            InfoContents.Visible = false;
            InfoPlaceholder.Visible = true;
            return;
        }

        foreach (var borgSubtype in subtypes)
        {
            var button = new Button
            {
                Text = PrototypeName(borgSubtype),
                Group = chassisGroup,
            };
            button.OnPressed += _ =>
            {
                _selectedBorgSubtype = borgSubtype;
                UpdateInformation(borgSubtype);
            };
            ChassisSelectionsContainer.AddChild(button);
        }

        InfoContents.Visible = false;
        InfoPlaceholder.Visible = true;
        ConfirmChassisButton.Disabled = true;
    }

    private void UpdateInformation(BorgSubtypePrototype prototype)
    {
        _selectedBorgSubtype = prototype;

        InfoContents.Visible = true;
        InfoPlaceholder.Visible = false;
        ConfirmChassisButton.Disabled = false;

        NameLabel.Text = PrototypeName(prototype);
        DescriptionLabel.Text = Loc.GetString($"borg-subtype-{prototype.ID}-desc");
        ChassisView.SetPrototype(prototype.DummyPrototype);
    }

    private void ConfirmButtonPressed(BaseButton.ButtonEventArgs obj)
    {
        if (_selectedBorgSubtype == null)
            return;

        var customName = string.IsNullOrEmpty(RenameInput.Text) ? null : RenameInput.Text;
        ConfirmedChassisSelection?.Invoke(_selectedBorgSubtype, customName);
    }

    private static string PrototypeName(BorgTypePrototype prototype)
    {
        return Loc.GetString($"borg-type-{prototype.ID}-name");
    }

    private static string PrototypeName(BorgSubtypePrototype prototype)
    {
        return Loc.GetString($"borg-subtype-{prototype.ID}-name");
    }
}
